name: flutter_experimental
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  appcheck: ^1.5.4+1
  biometric_signature: ^6.1.0
  camera: ^0.11.1
  dashbook: ^0.1.16
  device_info_plus: ^11.3.0
  dio: ^5.7.0
  dropdown_search: ^6.0.2
  face_verify: ^0.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  get_apps: ^1.0.4
  google_fonts: ^6.2.1
  jailbreak_root_detection: ^1.1.5
  location: ^8.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  security_plus: ^3.0.1
  vpn_connection_detector: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/user1.jpg
    - assets/models/facenet.tflite
    - assets/images/
    - assets/models/
